ref1 = "1&nbsp;<b>Oudtshoorn Lidmaatregister</b><br><i>Aangenomen te oudtshoorn op den 3 July 1868<br>Matthys Johannes BOOYSEN, *14 Des 1849 (Rietvallei) Matth.z<br><br></i>His death notice of 1933 gives the place of birth."
ref2 = "2&nbsp;<b>Martin Booyens - direct descendant and keeper of the family </b>"
ref3 = "3&nbsp;<b>Cape Archives</b><br>KAB MOOC Vol. No. 6/9/4349 Ref. 39642, Description: Booyens, Matthys Johannes. Estate Papers. (1933)"
ref4 = "4&nbsp;<b>Cape Archives</b><br>KAB MOOC Vol. No. 6/9/4349 Ref. 39642<br>Description: Booyens, Matthys Johannes. Estate Papers. (1933) <br><br><b>Dutch Reformed Church Records (originals)</b><br>Marriage books of the Oudtshoorn Parish: Marriage #1069 Booyens, Matthys Johannes, 25 Sep. 1876"
ref5 = "5&nbsp;<b>Oudtshoorn Lidmaatregister</b><br><i>AANGENOMEN DEN 3 JULY 1874<br>JONGEDOCHTERS<br>Susanna Johanna Hermina REDELINGHUYS, *1 Nov 1857 (Rietvallei)</i> "
