ref1 = "1&nbsp;<b>Dutch Reformed Church Registers (LDS on WWW)</b><br>Baptism Index 1855-1875 A-C<br>NAAM: Marthinus Jacobus<br>DATUM: 2.11.1868<br>PLEK: Willowmore<br>BOEK: 31<br>BLADSY: 493<br><br>ONLINE: https://familysearch.org/ark:/61903/3:1:33S7-9Y4D-R2G?i=144 "
ref2 = "2&nbsp;<b>Willowmore NGK Marriages</b><br>No 301"
ref3 = "3&nbsp;<b>Dutch Reformed Church Records (originals)</b><br>Oudtshoorn Parish Baptism Books<br>Geboren:  ## Mei 1894 <br>Gedoopt: 21 Junie 1894 <br><br>Maria Christiana<br><br>v. Christiaan Johan Frederik Schnetler<br>m. johanna Christina susanna ^Payne<br><br>get. Gideon Stephanus Muller<br>----  Andriesina H. Nortier<br><br>Doopouders:<br>Marthinus Jacobus Booyens<br>Maria C. Schnetler."
ref4 = "4&nbsp;<b>Dutch Reformed Church Records (originals)</b><br>Oudsthoorn Parish Baptism Book<br>Geboren:  ## Mei 1894 <br>Gedoopt: 21 Junie 1894 <br><br>Maria Christiana<br><br>v. Christiaan Johan Frederik Schnetler<br>m. johanna Christina susanna ^Payne<br><br>get. Gideon Stephanus Muller<br>----  Andriesina H. Nortier<br><br>Doopouders:<br>Marthinus Jacobus Booyens<br>Maria C. Schnetler."
ref5 = "5&nbsp;<b>Little Karoo Dutch Reformed Church Register</b>, courtesy of W.P. Jordaan & Alta le Roux<br>Baptism 1935"
ref6 = "6&nbsp;<b>Little Karoo Dutch Reformed Church Register</b>, courtesy of W.P. Jordaan & Alta le Roux<br>Baptism 1935"
ref7 = "7&nbsp;<b>Little Karoo Dutch Reformed Church Register</b>, courtesy of W.P. Jordaan & Alta le Roux<br>Prins Albert Doop 2347"
ref8 = "8&nbsp;<b>Little Karoo Dutch Reformed Church Register</b>, courtesy of W.P. Jordaan & Alta le Roux<br>Prins Albert Doop 2347"
ref9 = "9&nbsp;<b>Little Karoo Dutch Reformed Church Register</b>, courtesy of W.P. Jordaan & Alta le Roux<br>Prins Albert Doop 2650"
ref10 = "10&nbsp;<b>Little Karoo Dutch Reformed Church Register</b>, courtesy of W.P. Jordaan & Alta le Roux<br>Prins Albert Doop 2650"
ref11 = "11&nbsp;<b>Little Karoo Dutch Reformed Church Register</b>, courtesy of W.P. Jordaan & Alta le Roux<br>Prins Albert Doop 159"
ref12 = "12&nbsp;<b>Little Karoo Dutch Reformed Church Register</b>, courtesy of W.P. Jordaan & Alta le Roux<br>Prins Albert Doop 159"
